/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "open-cluster-management.io/cluster-permission/apis/v1alpha1"
	scheme "open-cluster-management.io/cluster-permission/client/clientset/versioned/scheme"
)

// ClusterPermissionsGetter has a method to return a ClusterPermissionInterface.
// A group's client should implement this interface.
type ClusterPermissionsGetter interface {
	ClusterPermissions(namespace string) ClusterPermissionInterface
}

// ClusterPermissionInterface has methods to work with ClusterPermission resources.
type ClusterPermissionInterface interface {
	Create(ctx context.Context, clusterPermission *v1alpha1.ClusterPermission, opts v1.CreateOptions) (*v1alpha1.ClusterPermission, error)
	Update(ctx context.Context, clusterPermission *v1alpha1.ClusterPermission, opts v1.UpdateOptions) (*v1alpha1.ClusterPermission, error)
	UpdateStatus(ctx context.Context, clusterPermission *v1alpha1.ClusterPermission, opts v1.UpdateOptions) (*v1alpha1.ClusterPermission, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterPermission, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterPermissionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterPermission, err error)
	ClusterPermissionExpansion
}

// clusterPermissions implements ClusterPermissionInterface
type clusterPermissions struct {
	client rest.Interface
	ns     string
}

// newClusterPermissions returns a ClusterPermissions
func newClusterPermissions(c *ApisV1alpha1Client, namespace string) *clusterPermissions {
	return &clusterPermissions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterPermission, and returns the corresponding clusterPermission object, and an error if there is any.
func (c *clusterPermissions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterPermission, err error) {
	result = &v1alpha1.ClusterPermission{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterpermissions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterPermissions that match those selectors.
func (c *clusterPermissions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterPermissionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterPermissionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterpermissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterPermissions.
func (c *clusterPermissions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterpermissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterPermission and creates it.  Returns the server's representation of the clusterPermission, and an error, if there is any.
func (c *clusterPermissions) Create(ctx context.Context, clusterPermission *v1alpha1.ClusterPermission, opts v1.CreateOptions) (result *v1alpha1.ClusterPermission, err error) {
	result = &v1alpha1.ClusterPermission{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterpermissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPermission).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterPermission and updates it. Returns the server's representation of the clusterPermission, and an error, if there is any.
func (c *clusterPermissions) Update(ctx context.Context, clusterPermission *v1alpha1.ClusterPermission, opts v1.UpdateOptions) (result *v1alpha1.ClusterPermission, err error) {
	result = &v1alpha1.ClusterPermission{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterpermissions").
		Name(clusterPermission.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPermission).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterPermissions) UpdateStatus(ctx context.Context, clusterPermission *v1alpha1.ClusterPermission, opts v1.UpdateOptions) (result *v1alpha1.ClusterPermission, err error) {
	result = &v1alpha1.ClusterPermission{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterpermissions").
		Name(clusterPermission.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterPermission).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterPermission and deletes it. Returns an error if one occurs.
func (c *clusterPermissions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterpermissions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterPermissions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterpermissions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterPermission.
func (c *clusterPermissions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterPermission, err error) {
	result = &v1alpha1.ClusterPermission{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterpermissions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
